In [9]:
import gymnasium as gym
from environments import CantStopEnv, CantStopActionSpace

import numpy as np

In [14]:
cs = CantStopEnv(num_players=3)
cs.roll_dice()
cs.dice
print(cs.dice)
cs._get_dice_combinations()

[2 2 4 5]


{(4, 9), (6, 7)}

In [17]:
# cs.tmp_marker_positions[3] = 4
# cs.tmp_marker_positions[7] = 12
cs.tmp_marker_positions[5] = 8
cs.player_marker_positions[0][7] = 12
# cs.tmp_marker_positions[6] = 8
print(cs._get_available_columns())
cs._get_possible_moves()

{2, 3, 4, 6, 8, 9, 10, 11, 12}


[(4, 9), (6,)]

In [5]:
tmp_pos = cs.tmp_marker_positions
tmp_pos[4] = 2
tmp_pos[5] = 9
free_temp_markers = 3 - sum(level is not None for level in tmp_pos.values())
free_temp_markers

1

In [6]:
cs._get_possible_moves()

[(6, 8), (6, 8), (4, 10)]

In [3]:
cs.player_marker_positions[1][3] = 2 # middle pos, player 1, column 3
cs.player_marker_positions[2][7] = 12 # top pos, player 2, column 7
cs.player_marker_positions[0][3] = 4
cs.player_marker_positions

{0: {2: None,
  3: 4,
  4: None,
  5: None,
  6: None,
  7: None,
  8: None,
  9: None,
  10: None,
  11: None,
  12: None},
 1: {2: None,
  3: 2,
  4: None,
  5: None,
  6: None,
  7: None,
  8: None,
  9: None,
  10: None,
  11: None,
  12: None},
 2: {2: None,
  3: None,
  4: None,
  5: None,
  6: None,
  7: 12,
  8: None,
  9: None,
  10: None,
  11: None,
  12: None}}

In [4]:
cs._get_available_columns()

array([ 2,  4,  5,  6,  8,  9, 10, 11, 12])

In [7]:
any(cs.player_marker_positions[player][column] == cs.column_lengths - 1 for column in player for player, column in cs.player_marker_positions.values())

{2: 3, 3: 5, 4: 7, 5: 9, 6: 11, 7: 13, 8: 11, 9: 9, 10: 7, 11: 5, 12: 3}

In [6]:
dice = cs.roll_dice()
print(dice)
combos = cs._get_dice_combinations(dice)
print(combos)

[5 6 1 5]
[(11, 6), (6, 11), (10, 7)]


In [13]:
csas = CantStopActionSpace()
for _ in range(100000): 
    sample = csas.sample()
    if not csas.contains(sample):
        print(sample)

In [9]:
two_col = [[' ']] * 3
two_col[0] = ['$']
two_col[1] = ['%/&']
two_col

[['$'], ['%/&'], [' ']]

In [18]:
num_players = 3
columns = np.arange(start=2, stop=13)

player_marker_positions = {p: {c: None for c in columns} for p in range(num_players)}
player_marker_positions

{0: {2: None,
  3: None,
  4: None,
  5: None,
  6: None,
  7: None,
  8: None,
  9: None,
  10: None,
  11: None,
  12: None},
 1: {2: None,
  3: None,
  4: None,
  5: None,
  6: None,
  7: None,
  8: None,
  9: None,
  10: None,
  11: None,
  12: None},
 2: {2: None,
  3: None,
  4: None,
  5: None,
  6: None,
  7: None,
  8: None,
  9: None,
  10: None,
  11: None,
  12: None}}

In [46]:
from itertools import combinations, permutations

available_columns = set([2, 3, 4, 5, 6, 7, 9, 10, 11, 12])
tmp_columns = set([6, 12])
free_tmp_markers = 3 - len(tmp_columns)

combos = [(6, 7), (5, 8), (4, 9)]

for comb in combos:
    comb_avail = set(comb) & available_columns
    if len(comb_avail) == 0: continue
    if free_tmp_markers == 0:
        print('A')
        print(comb_avail & tmp_columns)
        print()
        continue
    
    if len(comb_avail - tmp_columns) <= free_tmp_markers:
        print('B')
        print(comb_avail)
        print()
        continue
    
    print('C')
    print(list(combinations(comb_avail - tmp_columns, free_tmp_markers)))
    print()
    # len(comb_avail & tmp_columns)
    # print(comb_avail)

B
{6, 7}

B
{5}

C
[(9,), (4,)]


In [24]:
a = set([2, 3, 9, 4])
b = set([3, 4, 5])
a - b

{2, 9}